# roles/echo-role/tasks/main.yml
- name: Echo localhost
  ansible.builtin.debug:
    msg: "This is localhost"
  when: "'local' in group_names"

- name: Echo server
  ansible.builtin.debug:
    msg: "This is server"
  when: "'server' in group_names"
